### PR TITLE
Reorganize workspaces related to training

### PR DESCRIPTION
**Pull request by kampersanda**
This PR moves the cli tools `dictgen`, `evaluate`, and `split` under the directory `train`.
This is the first step of https://github.com/daac-tools/vibrato/issues/68, and after this, I will update the document configuration.

### CODE REVIEW

**Review by vbkaisetsu — COMMENTED** [review]
On second thought, I would prefer not to have multiple binaries in one crate.

First, the executable named `evaluate` is contained in the `train` crate, but it is unnatural because `evaluate` does the opposite of `train`.
Second, some binaries must depend on unnecessary libraries. For example, `dictgen` does not require the `rand` crate.

I would rather have separate crates for each executable and not use the `[[bin]]` section.

**Comment by vbkaisetsu** [comment]
Furthermore, Cargo places all executables under `target/{debug,release}`, so using `workspace` and `bin` together may cause binary name conflicts.

**Comment by kampersanda** [comment]
@vbkaisetsu I see. The first objective is to separate advanced documentation from easy documentation. Your opinion also makes sense. Then, how about creating the directory `docs` and placing advanced documents (i.e., ones related to `train` and `prepare`) there?

**Comment by vbkaisetsu** [comment]
@kampersanda 👍

**Comment by kampersanda** [comment]
@vbkaisetsu Thanks. I'll create another PR.

**Pull request closed without merging**
